import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('ur'),
  ];

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(localizations != null, 'AppLocalizations not found in context.');
    return localizations!;
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'appName': 'PPMS Tenant',
      'loginTitle': 'Sign in to your station workspace',
      'loginSubtitle':
          'Use your staff account to open only the modules and actions assigned to you.',
      'username': 'Username',
      'password': 'Password',
      'signIn': 'Sign in',
      'demoAccounts': 'Seeded local accounts',
      'loadingSession': 'Restoring your session',
      'loadingSessionHint':
          'Checking your saved login, enabled modules, and scope access.',
      'forbidden': 'Access restricted',
      'forbiddenHint':
          'Your account is active, but this area is outside your current role or scope.',
      'backToHome': 'Back to home',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'overview': 'Overview',
      'managerWorkspace': 'Shift workspace',
      'operatorWorkspace': 'Self service',
      'accountantWorkspace': 'Finance workspace',
      'stationAdminWorkspace': 'Station control',
      'headOfficeWorkspace': 'Organization control',
      'masterAdminWorkspace': 'Onboarding workspace',
      'logout': 'Log out',
      'language': 'Language',
      'english': 'English',
      'urdu': 'Urdu',
      'activeModules': 'Enabled modules',
      'featureFlags': 'Feature flags',
      'permissions': 'Permission summary',
      'quickStatus': 'Quick status',
      'apiBaseUrl': 'API base URL',
      'currentRole': 'Current role',
      'scopeLevel': 'Scope level',
      'organization': 'Organization',
      'station': 'Station',
      'sessionReady': 'Foundation ready',
      'sessionReadyHint':
          'Auth, localization, responsive shell, and module-aware navigation are wired.',
      'notificationsEmpty':
          'Notification center shell is ready for in-app events and future WhatsApp/Firebase delivery.',
      'profileHint':
          'This area will hold personal details, attendance, payroll, and account settings based on role.',
      'workspaceHint':
          'This workspace shell is ready for the next feature build phase.',
      'menu': 'Menu',
      'sessionRestore': 'Session restore',
      'signInFailed': 'Sign-in failed',
      'roleModules': 'Role and modules',
      'refreshHint':
          'Session refresh automation will be added after the next API integration step.',
      'organizations': 'Organizations',
      'noOrganizationsYet': 'No organizations yet.',
      'open': 'Open',
      'configure': 'Configure',
      'onboardingProgress': 'Onboarding progress',
      'onboardingProgressHint':
          'Select an organization to see its setup progress and blockers.',
      'stationChecklist': 'Station checklist',
      'stationChecklistHint':
          'Station setup cards appear here after you open an organization.',
      'topIssues': 'Top issues',
      'masterAdminTitle': 'MasterAdmin onboarding workspace',
      'masterAdminSubtitle':
          'Complete organization basics first, then move into station planning, modules, and first-admin handoff.',
      'organizationBasicsStep': 'Organization basics',
      'stationPlanningStep': 'Station planning',
      'adminStep': 'First admin and next actions',
      'organizationName': 'Organization name',
      'legalName': 'Legal name',
      'sameAsOrganizationName': 'Use organization name as legal name',
      'brand': 'Brand',
      'noBrand': 'No brand',
      'stationCount': 'Station count',
      'contactEmail': 'Contact email',
      'contactPhone': 'Contact phone',
      'registrationNumber': 'Registration number',
      'taxNumber': 'Tax / GST number',
      'inheritBrandingToStations': 'Inherit branding to stations',
      'organizationActive': 'Organization active',
      'moduleToggles': 'Module toggles',
      'firstAdmin': 'First admin',
      'adminFullName': 'Admin full name',
      'adminUsername': 'Admin username',
      'adminPassword': 'Admin password',
      'adminEmail': 'Admin email',
      'adminPhone': 'Admin phone',
      'createOrganization': 'Create organization',
      'updateOrganization': 'Update organization',
      'startNew': 'Start new',
      'onboardingSaved': 'Onboarding details saved.',
      'stationDraftsTitle': 'Station drafts',
      'stationDraftsHint':
          'Auto-generate the station rows from count, then edit names, codes, and head-office mapping before saving.',
      'stationDraftsSingleHint':
          'Single-station organizations keep one combined HeadOffice/StationAdmin path.',
      'stationName': 'Station name',
      'stationCode': 'Station code',
      'headOfficeStation': 'Head office station',
      'activeStation': 'Active station',
      'brandPreview': 'Brand preview',
      'stationSetupTitle': 'Station setup wizard',
      'stationSetupSaved': 'Station setup saved.',
      'quickPlanner': 'Quick planner',
      'quickPlannerHint':
          'Start with counts, generate default rows, then edit the rows in detail.',
      'generateDefaults': 'Generate defaults',
      'fuelTypeCount': 'Fuel type count',
      'tankCount': 'Tank count',
      'dispenserCount': 'Dispenser count',
      'nozzlesPerDispenser': 'Default nozzles per dispenser',
      'displayName': 'Display name',
      'shiftMode': 'Shift mode',
      'hour24': '24 hour',
      'twoBy12': '2 x 12 hour',
      'threeBy8': '3 x 8 hour',
      'fuelTypes': 'Fuel types',
      'tanks': 'Tanks',
      'dispensersAndNozzles': 'Dispensers and nozzles',
      'add': 'Add',
      'saveStationSetup': 'Save station setup',
      'fuelTypeName': 'Fuel type name',
      'description': 'Description',
      'tankName': 'Tank name',
      'code': 'Code',
      'fuelType': 'Fuel type',
      'capacity': 'Capacity',
      'lowStockThreshold': 'Low stock threshold',
      'active': 'Active',
      'dispenserName': 'Dispenser name',
      'addNozzle': 'Add nozzle',
      'nozzleName': 'Nozzle name',
      'tank': 'Tank',
      'startingMeter': 'Starting meter',
      'startingMeterHint':
          'Only the starting reading is set here. Live operational meter movement happens later in station use.',
      'operatorTitle': 'Operator self service',
      'operatorSubtitle':
          'This role is limited to personal profile, attendance, payroll, and notifications.',
      'managerTitle': 'Manager shift workspace',
      'managerSubtitle':
          'Open the current shift, record cash movement, enter nozzle closings, and validate before closing.',
      'shiftPrepared': 'Prepared shift',
      'shiftOpen': 'Open shift',
      'shiftOccupied': 'Shift with another manager',
      'shiftMissingTemplate': 'Missing shift template',
      'openingCash': 'Opening cash',
      'startCurrentShift': 'Start current shift',
      'shiftTemplate': 'Shift template',
      'shiftMessage': 'Shift status',
      'cashInHand': 'Cash in hand',
      'expectedCash': 'Expected cash',
      'cashSubmitted': 'Cash submitted',
      'openingCashCarryForward': 'Opening cash carried forward',
      'cashSubmittedSoFar': 'Cash submitted so far',
      'remainingCashInHand': 'Remaining cash in hand',
      'nextShiftCarryForward': 'Next shift carry-forward',
      'cashVarianceLabel': 'Cash variance',
      'submitCash': 'Submit cash',
      'submissionAmount': 'Submission amount',
      'recentCashSubmissions': 'Recent cash submissions',
      'dispenserChecklist': 'Dispenser checklist',
      'closingMeter': 'Closing meter',
      'mappedTank': 'Mapped tank',
      'closeShift': 'Close shift',
      'runCloseCheck': 'Run close check',
      'closeValidation': 'Close validation',
      'warnings': 'Warnings',
      'blockingIssues': 'Blocking issues',
      'actualCashCollected': 'Actual cash counted',
      'closingCashLeftInHand': 'Closing cash left in hand',
      'closingCashLeftInHandHint':
          'Enter the change cash that will remain with the shift and carry forward to the next shift.',
      'managerNoShift':
          'No active shift is open yet. Use the prepared current shift for this station.',
      'managerShiftOccupied':
          'Another manager is still on shift. You can start only after that shift is closed and handed over.',
      'shiftStartedAt': 'Started at',
      'runCloseHint': 'Run close check to see blockers and warnings.',
      'openingMeter': 'Opening meter',
      'currentMeter': 'Current meter',
      'meterAdjustedFlag': 'Meter adjusted',
      'managerTotals': 'Shift totals',
      'fuelSalesCard': 'Fuel sales',
      'lubricantSalesCard': 'Lubricant sales',
      'receivingCard': 'Receiving',
      'expenseCard': 'Expenses',
      'recoveryCard': 'Credit recovery',
      'internalUsageCard': 'Internal usage',
      'managerNotifications': 'Notifications',
      'liters': 'liters',
      'entries': 'entries',
      'totalLabel': 'total',
      'creditFollowUps': 'Credit follow-ups',
      'noPendingFollowUps': 'No pending follow-ups right now.',
      'recentDipActivity': 'Recent dip activity',
      'noRecentItems': 'No recent activity yet.',
      'managerActions': 'Manager actions',
      'recordDipAction': 'Record dip',
      'recordReceivingAction': 'Record receiving',
      'customerCreditAction': 'Customer credit',
      'creditRecoveryAction': 'Credit recovery',
      'creditGivenAction': 'Credit given',
      'creditGivenCard': 'Credit given',
      'creditGivenAmount': 'Credit amount',
      'giveCreditNow': 'Give credit',
      'recoverNow': 'Recover now',
      'increaseCreditAction': 'Increase credit',
      'recordExpenseAction': 'Record expense',
      'sellLubricantAction': 'Sell lubricant',
      'internalUsageAction': 'Record internal usage',
      'dipReadingMm': 'Dip reading (mm)',
      'optionalNotes': 'Optional notes',
      'supplier': 'Supplier',
      'quantity': 'Quantity',
      'ratePerLiter': 'Rate per liter',
      'dipBefore': 'Dip before',
      'dipAfter': 'Dip after',
      'referenceGrn': 'Reference / GRN',
      'customer': 'Customer',
      'outstandingLabel': 'Outstanding',
      'creditLimitLabel': 'Credit limit',
      'recoveredAmount': 'Recovered amount',
      'referenceNumber': 'Reference number',
      'increaseBy': 'Increase by',
      'reasonOptional': 'Reason (optional)',
      'topCreditList': 'Top credit list',
      'expenseCategory': 'Expense category',
      'amount': 'Amount',
      'product': 'Product',
      'stockLabel': 'stock',
      'vehiclePurpose': 'Vehicle / purpose',
      'operatorActionSuccess': 'Action completed',
      'attendanceCard': 'Attendance',
      'attendanceDisabled': 'Attendance is not enabled for this account.',
      'todayStatus': 'Today status',
      'checkedInAt': 'Checked in at',
      'checkedOutAt': 'Checked out at',
      'checkIn': 'Check in',
      'checkOut': 'Check out',
      'recentAttendance': 'Recent attendance',
      'payrollSummary': 'Payroll summary',
      'payrollDisabled': 'Payroll is not enabled for this account.',
      'currentSalary': 'Current salary',
      'latestPayroll': 'Latest payroll',
      'grossAmount': 'Gross amount',
      'deductions': 'Deductions',
      'netAmount': 'Net amount',
      'bonusAmount': 'Bonus / additions',
      'attendanceDeduction': 'Attendance deduction',
      'recentPayrollHistory': 'Recent payroll history',
      'noPayrollHistory': 'No payroll history yet.',
      'employeeDetails': 'Employee details',
      'staffTitle': 'Staff title',
      'employeeCode': 'Employee code',
      'hasNoEmployeeProfile':
          'No linked employee profile exists yet. The login account is active, but HR details still need completion.',
      'saveFailed': 'Save failed',
      'loadFailed': 'Load failed',
    },
    'ur': {
      'appName': 'پی پی ایم ایس ٹیننٹ',
      'loginTitle': 'اپنے اسٹیشن ورک اسپیس میں سائن اِن کریں',
      'loginSubtitle':
          'اپنے اسٹاف اکاؤنٹ سے صرف وہی ماڈیول اور ایکشن کھولیں جو آپ کو دیے گئے ہیں۔',
      'username': 'یوزرنیم',
      'password': 'پاس ورڈ',
      'signIn': 'سائن اِن',
      'demoAccounts': 'لوکل سیڈ اکاؤنٹس',
      'loadingSession': 'سیشن بحال کیا جا رہا ہے',
      'loadingSessionHint':
          'آپ کا محفوظ لاگ اِن، فعال ماڈیولز، اور اسکوپ ایکسیس چیک کی جا رہی ہے۔',
      'forbidden': 'رسائی محدود ہے',
      'forbiddenHint':
          'آپ کا اکاؤنٹ فعال ہے لیکن یہ حصہ آپ کے موجودہ رول یا اسکوپ سے باہر ہے۔',
      'backToHome': 'ہوم پر واپس جائیں',
      'profile': 'پروفائل',
      'notifications': 'نوٹیفکیشنز',
      'overview': 'اوورویو',
      'managerWorkspace': 'شفٹ ورک اسپیس',
      'operatorWorkspace': 'سیلف سروس',
      'accountantWorkspace': 'فنانس ورک اسپیس',
      'stationAdminWorkspace': 'اسٹیشن کنٹرول',
      'headOfficeWorkspace': 'آرگنائزیشن کنٹرول',
      'masterAdminWorkspace': 'آن بورڈنگ ورک اسپیس',
      'logout': 'لاگ آؤٹ',
      'language': 'زبان',
      'english': 'English',
      'urdu': 'اردو',
      'activeModules': 'فعال ماڈیولز',
      'featureFlags': 'فیچر فلیگز',
      'permissions': 'پرمیژن خلاصہ',
      'quickStatus': 'فوری حالت',
      'apiBaseUrl': 'اے پی آئی بیس یو آر ایل',
      'currentRole': 'موجودہ رول',
      'scopeLevel': 'اسکوپ لیول',
      'organization': 'آرگنائزیشن',
      'station': 'اسٹیشن',
      'sessionReady': 'فاؤنڈیشن تیار ہے',
      'sessionReadyHint':
          'اتھ، لوکلائزیشن، ریسپانسیو شیل، اور ماڈیول کے مطابق نیویگیشن تیار ہے۔',
      'notificationsEmpty':
          'نوٹیفکیشن سینٹر شیل اِن ایپ ایونٹس اور آئندہ واٹس ایپ / فائر بیس ڈیلیوری کے لیے تیار ہے۔',
      'profileHint':
          'اس حصے میں ذاتی تفصیلات، حاضری، پے رول، اور اکاؤنٹ سیٹنگز رول کے مطابق آئیں گی۔',
      'workspaceHint': 'یہ ورک اسپیس اگلے فیچر مرحلے کے لیے تیار ہے۔',
      'menu': 'مینیو',
      'sessionRestore': 'سیشن بحالی',
      'signInFailed': 'سائن اِن ناکام',
      'roleModules': 'رول اور ماڈیولز',
      'refreshHint':
          'سیشن ریفریش آٹومیشن اگلے اے پی آئی انٹیگریشن مرحلے میں شامل ہوگی۔',
      'organizations': 'آرگنائزیشنز',
      'noOrganizationsYet': 'ابھی کوئی آرگنائزیشن موجود نہیں۔',
      'open': 'کھولیں',
      'configure': 'ترتیب دیں',
      'onboardingProgress': 'آن بورڈنگ پیش رفت',
      'onboardingProgressHint':
          'پیش رفت اور رکاوٹیں دیکھنے کے لیے ایک آرگنائزیشن منتخب کریں۔',
      'stationChecklist': 'اسٹیشن چیک لسٹ',
      'stationChecklistHint':
          'آرگنائزیشن کھولنے کے بعد اسٹیشن سیٹ اپ کارڈز یہاں نظر آئیں گے۔',
      'topIssues': 'اہم مسائل',
      'masterAdminTitle': 'ماسٹر ایڈمن آن بورڈنگ ورک اسپیس',
      'masterAdminSubtitle':
          'پہلے آرگنائزیشن کی بنیادی تفصیلات مکمل کریں، پھر اسٹیشن پلاننگ، ماڈیولز، اور پہلے ایڈمن کی ہینڈ آف کریں۔',
      'organizationBasicsStep': 'آرگنائزیشن کی بنیادیات',
      'stationPlanningStep': 'اسٹیشن پلاننگ',
      'adminStep': 'پہلا ایڈمن اور اگلے اقدامات',
      'organizationName': 'آرگنائزیشن کا نام',
      'legalName': 'قانونی نام',
      'sameAsOrganizationName': 'قانونی نام آرگنائزیشن کے نام جیسا رکھیں',
      'brand': 'برانڈ',
      'noBrand': 'کوئی برانڈ نہیں',
      'stationCount': 'اسٹیشن کی تعداد',
      'contactEmail': 'رابطہ ای میل',
      'contactPhone': 'رابطہ فون',
      'registrationNumber': 'رجسٹریشن نمبر',
      'taxNumber': 'ٹیکس / جی ایس ٹی نمبر',
      'inheritBrandingToStations': 'برانڈنگ اسٹیشنز کو منتقل کریں',
      'organizationActive': 'آرگنائزیشن فعال ہے',
      'moduleToggles': 'ماڈیول ٹوگلز',
      'firstAdmin': 'پہلا ایڈمن',
      'adminFullName': 'ایڈمن کا پورا نام',
      'adminUsername': 'ایڈمن یوزرنیم',
      'adminPassword': 'ایڈمن پاس ورڈ',
      'adminEmail': 'ایڈمن ای میل',
      'adminPhone': 'ایڈمن فون',
      'createOrganization': 'آرگنائزیشن بنائیں',
      'updateOrganization': 'آرگنائزیشن اپڈیٹ کریں',
      'startNew': 'نیا شروع کریں',
      'onboardingSaved': 'آن بورڈنگ تفصیلات محفوظ ہو گئیں۔',
      'stationDraftsTitle': 'اسٹیشن ڈرافٹس',
      'stationDraftsHint':
          'تعداد سے اسٹیشن قطاریں بنائیں، پھر نام، کوڈ، اور ہیڈ آفس میپنگ محفوظ کرنے سے پہلے ایڈٹ کریں۔',
      'stationDraftsSingleHint':
          'ایک اسٹیشن والی آرگنائزیشن میں ہیڈ آفس اور اسٹیشن ایڈمن کا راستہ ایک ہی رہتا ہے۔',
      'stationName': 'اسٹیشن کا نام',
      'stationCode': 'اسٹیشن کوڈ',
      'headOfficeStation': 'ہیڈ آفس اسٹیشن',
      'activeStation': 'فعال اسٹیشن',
      'brandPreview': 'برانڈ پری ویو',
      'stationSetupTitle': 'اسٹیشن سیٹ اپ وزرڈ',
      'stationSetupSaved': 'اسٹیشن سیٹ اپ محفوظ ہو گیا۔',
      'quickPlanner': 'فوری پلانر',
      'quickPlannerHint':
          'پہلے تعداد منتخب کریں، ڈیفالٹ قطاریں بنائیں، پھر تفصیل میں ترمیم کریں۔',
      'generateDefaults': 'ڈیفالٹس بنائیں',
      'fuelTypeCount': 'فیول ٹائپس کی تعداد',
      'tankCount': 'ٹینکس کی تعداد',
      'dispenserCount': 'ڈسپنسرز کی تعداد',
      'nozzlesPerDispenser': 'ہر ڈسپنسر کے لیے ڈیفالٹ نوزلز',
      'displayName': 'ڈسپلے نام',
      'shiftMode': 'شفٹ موڈ',
      'hour24': '24 گھنٹے',
      'twoBy12': '2 x 12 گھنٹے',
      'threeBy8': '3 x 8 گھنٹے',
      'fuelTypes': 'فیول ٹائپس',
      'tanks': 'ٹینکس',
      'dispensersAndNozzles': 'ڈسپنسرز اور نوزلز',
      'add': 'شامل کریں',
      'saveStationSetup': 'اسٹیشن سیٹ اپ محفوظ کریں',
      'fuelTypeName': 'فیول ٹائپ نام',
      'description': 'تفصیل',
      'tankName': 'ٹینک نام',
      'code': 'کوڈ',
      'fuelType': 'فیول ٹائپ',
      'capacity': 'کیپیسٹی',
      'lowStockThreshold': 'کم اسٹاک حد',
      'active': 'فعال',
      'dispenserName': 'ڈسپنسر نام',
      'addNozzle': 'نوزل شامل کریں',
      'nozzleName': 'نوزل نام',
      'tank': 'ٹینک',
      'startingMeter': 'ابتدائی میٹر',
      'startingMeterHint':
          'یہاں صرف ابتدائی ریڈنگ سیٹ کی جاتی ہے۔ لائیو میٹر موومنٹ بعد میں اسٹیشن استعمال میں ہوگی۔',
      'operatorTitle': 'آپریٹر سیلف سروس',
      'operatorSubtitle':
          'یہ رول صرف ذاتی پروفائل، حاضری، پے رول، اور نوٹیفکیشنز تک محدود ہے۔',
      'managerTitle': 'منیجر شفٹ ورک اسپیس',
      'managerSubtitle':
          'موجودہ شفٹ کھولیں، نقدی کی حرکت درج کریں، نوزل کلوزنگ دیں، اور بند کرنے سے پہلے چیک کریں۔',
      'shiftPrepared': 'تیار شفٹ',
      'shiftOpen': 'کھلی شفٹ',
      'shiftOccupied': 'دوسرے منیجر کے ساتھ شفٹ',
      'shiftMissingTemplate': 'شفٹ ٹیمپلیٹ موجود نہیں',
      'openingCash': 'اوپننگ کیش',
      'startCurrentShift': 'موجودہ شفٹ شروع کریں',
      'shiftTemplate': 'شفٹ ٹیمپلیٹ',
      'shiftMessage': 'شفٹ حالت',
      'cashInHand': 'کیش اِن ہینڈ',
      'expectedCash': 'متوقع کیش',
      'cashSubmitted': 'جمع شدہ کیش',
      'openingCashCarryForward': 'پچھلی شفٹ سے لائی گئی اوپننگ کیش',
      'cashSubmittedSoFar': 'اب تک جمع کروائی گئی کیش',
      'remainingCashInHand': 'باقی کیش اِن ہینڈ',
      'nextShiftCarryForward': 'اگلی شفٹ کے لیے کیش',
      'cashVarianceLabel': 'کیش ویریئنس',
      'submitCash': 'کیش جمع کریں',
      'submissionAmount': 'جمع شدہ رقم',
      'recentCashSubmissions': 'حالیہ کیش جمع کرائیاں',
      'dispenserChecklist': 'ڈسپنسر چیک لسٹ',
      'closingMeter': 'کلوزنگ میٹر',
      'mappedTank': 'منسلک ٹینک',
      'closeShift': 'شفٹ بند کریں',
      'runCloseCheck': 'کلوز چیک چلائیں',
      'closeValidation': 'کلوز ویلیڈیشن',
      'warnings': 'وارننگز',
      'blockingIssues': 'رکاوٹ والے مسائل',
      'actualCashCollected': 'اصل گنی گئی کیش',
      'closingCashLeftInHand': 'اختتام پر ہاتھ میں بچی کیش',
      'closingCashLeftInHandHint':
          'وہ چینج کیش درج کریں جو شفٹ کے پاس رہے گی اور اگلی شفٹ میں منتقل ہوگی۔',
      'managerNoShift':
          'ابھی کوئی فعال شفٹ کھلی نہیں۔ اس اسٹیشن کی تیار شدہ موجودہ شفٹ استعمال کریں۔',
      'managerShiftOccupied':
          'ایک اور منیجر ابھی اس شفٹ پر ہے۔ نئی شفٹ اسی وقت شروع ہوگی جب پچھلی شفٹ بند ہو کر ہینڈ اوور ہو جائے۔',
      'operatorActionSuccess': 'عمل مکمل ہو گیا',
      'attendanceCard': 'حاضری',
      'attendanceDisabled': 'اس اکاؤنٹ کے لیے حاضری فعال نہیں ہے۔',
      'todayStatus': 'آج کی حالت',
      'checkedInAt': 'چیک اِن وقت',
      'checkedOutAt': 'چیک آؤٹ وقت',
      'checkIn': 'چیک اِن',
      'checkOut': 'چیک آؤٹ',
      'recentAttendance': 'حالیہ حاضری',
      'payrollSummary': 'پے رول خلاصہ',
      'payrollDisabled': 'اس اکاؤنٹ کے لیے پے رول فعال نہیں ہے۔',
      'currentSalary': 'موجودہ تنخواہ',
      'latestPayroll': 'تازہ پے رول',
      'grossAmount': 'کل رقم',
      'deductions': 'کٹوتیاں',
      'netAmount': 'خالص رقم',
      'bonusAmount': 'بونس / اضافے',
      'attendanceDeduction': 'حاضری کٹوتی',
      'recentPayrollHistory': 'حالیہ پے رول ہسٹری',
      'noPayrollHistory': 'ابھی پے رول ہسٹری موجود نہیں۔',
      'employeeDetails': 'ملازم کی تفصیلات',
      'staffTitle': 'اسٹاف ٹائٹل',
      'employeeCode': 'ملازم کوڈ',
      'hasNoEmployeeProfile':
          'ابھی لنکڈ ایمپلائی پروفائل موجود نہیں۔ لاگ اِن اکاؤنٹ فعال ہے مگر ایچ آر تفصیلات ابھی مکمل ہونی ہیں۔',
      'saveFailed': 'محفوظ کرنا ناکام ہوا',
      'loadFailed': 'لوڈ کرنا ناکام ہوا',
    },
  };

  String text(String key) =>
      _strings[locale.languageCode]?[key] ?? _strings['en']![key] ?? key;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any(
        (supportedLocale) => supportedLocale.languageCode == locale.languageCode,
      );

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
